CREATE TABLE `fh_bank_info` (
  `created_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '创建人',
  `created_date` datetime NOT NULL COMMENT '创建日期',
  `updated_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '修改人',
  `updated_date` datetime NOT NULL COMMENT '修改日期',
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '表ID',
  `report_no` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '报案号',
  `insured_man` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '被保险人',
  `client_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '客户名称',
  `client_type` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '客户类型',
  `account` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '账号',
  `payment_obj` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '支付对象',
  `purpose` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '用途',
  `card_type` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '卡折类型',
  `bank_type_code` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '银行类型',
  `bank_type_name` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '银行类型名称',
  `bank_region_code` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '银行区域',
  `bank_region_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '银行区域名称',
  `bank_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '开户行名称',
  `bank_code` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '开户行代码',
  `bank_location_code` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '银行网点编码',
  `bank_location_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '银行网点名称',
  `user_phone` varchar(15) COLLATE utf8_bin DEFAULT NULL COMMENT '用户电话号码',
  `remark` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_bank_rptno` (`report_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='银行信息';