CREATE TABLE `fh_car_info` (
  `created_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '创建人',
  `created_date` datetime NOT NULL COMMENT '创建日期',
  `updated_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '修改人',
  `updated_date` datetime NOT NULL COMMENT '修改日期',
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '表ID',
  `survey_id` bigint(20) DEFAULT NULL COMMENT '查勘ID',
  `car_mark` varchar(50) COLLATE utf8_bin NOT NULL COMMENT '车牌',
  `vin_no` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT '车架号',
  `engine_no` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '发动机号',
  `first_date` datetime DEFAULT NULL COMMENT '初登日期',
  `car_type` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '厂牌车型',
  `person_count` int(5) DEFAULT NULL COMMENT '案件发生时的乘客数',
  `is_drive` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '是否可以驾驶',
  `car_colour` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT '车辆颜色',
  `mileage_num` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '案发时公里数',
  `is_overload` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '是否超载',
  `overload_weight` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '超载重量',
  `mark_type` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT '号牌种类',
  `seat_count` int(5) DEFAULT NULL COMMENT '车辆座位数',
  `driving_license` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '出险车辆行驶证号码',
  `target_type` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '1=标的 2=三者',
  `remark` varchar(500) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `producer_name` varchar(120) COLLATE utf8_bin DEFAULT NULL COMMENT '生产厂家',
  `brand_name` varchar(150) COLLATE utf8_bin DEFAULT NULL COMMENT '品牌名称',
  `serial_name` varchar(60) COLLATE utf8_bin DEFAULT NULL COMMENT '车系名称',
  `type_code` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '车型代码',
  `type_name` varchar(120) COLLATE utf8_bin DEFAULT NULL COMMENT '车型名称',
  `class_name` varchar(60) COLLATE utf8_bin DEFAULT NULL COMMENT '车辆类型',
  `product_year` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '生产年份',
  PRIMARY KEY (`id`),
  KEY `idx_car_mark` (`car_mark`),
  KEY `idx_car_surveyid` (`survey_id`),
  KEY `idx_car_tgtype` (`target_type`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='车辆信息';