CREATE TABLE `fh_loss_item` (
  `created_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '创建人',
  `created_date` datetime NOT NULL COMMENT '创建日期',
  `updated_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '修改人',
  `updated_date` datetime NOT NULL COMMENT '修改日期',
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '表ID',
  `loss_id` bigint(20) NOT NULL COMMENT '定损ID',
  `insure_code` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '险种名称',
  `loss_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '物损名称',
  `standard` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '规格型号',
  `loss_count` int(5) DEFAULT NULL COMMENT '定损数量',
  `price` decimal(16,2) DEFAULT NULL COMMENT '单价',
  `loss_degree` int(3) DEFAULT NULL COMMENT '损失程度',
  `salvage` decimal(16,2) DEFAULT NULL COMMENT '定损残值',
  `total_amount` decimal(16,2) DEFAULT NULL COMMENT '损失合计',
  `audit_price` decimal(16,2) DEFAULT NULL COMMENT '核损单价',
  `audit_count` int(5) DEFAULT NULL COMMENT '核损数量',
  `audit_loss_degree` int(3) DEFAULT NULL COMMENT '核损损失程度',
  `audit_salvage` decimal(16,2) DEFAULT NULL COMMENT '核损残值',
  `audit_amount` decimal(16,2) DEFAULT NULL COMMENT '核损总额',
  `first_amount` decimal(16,2) DEFAULT NULL COMMENT '第一次定损总额',
  PRIMARY KEY (`id`),
  KEY `idx_lossitem_lossid` (`loss_id`)
) ENGINE=InnoDB AUTO_INCREMENT=147 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='物损项目信息';