CREATE TABLE `fh_survey_info` (
  `created_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '创建人',
  `created_date` datetime NOT NULL COMMENT '创建日期',
  `updated_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '修改人',
  `updated_date` datetime NOT NULL COMMENT '修改日期',
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '表ID',
  `accident_cause_big` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '出险原因大类',
  `accident_cause_small` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '出险原因小类',
  `accident_subcause` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '事故分类',
  `accident_area` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '出险区域',
  `dispose_dept` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '事故处理类型',
  `road_type` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '道路信息',
  `accident_duty` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '事故责任',
  `duty_percent` decimal(3,0) DEFAULT NULL COMMENT '事故责任比例',
  `is_injured` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '是否涉及人伤 1=是 2=否 3=不确定',
  `is_loss` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '是否包含财损 1=是 2=否 3=不确定',
  `accident_address` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '出险详细地址',
  `accident_province` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '出险区域-省',
  `accident_city` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '出险区域-市',
  `accident_county` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '出险区域-区、县、镇、乡',
  `accident_street` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '出险区域-街',
  `claim_action` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '理赔类型',
  `is_cali` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '互碰自赔标志，该值为1时存在三者信息，为0时不存在三者信息',
  `accident_course` varchar(500) COLLATE utf8_bin DEFAULT NULL COMMENT '出险经过',
  `user_code` bigint(20) DEFAULT NULL COMMENT '查勘员编码',
  `survey_time` datetime DEFAULT NULL COMMENT '查勘时间',
  `survey_place` varchar(200) COLLATE utf8_bin DEFAULT NULL COMMENT '查勘地点',
  `place_type` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT '查勘地点类型 CKDD',
  `survey_conclusion` varchar(500) COLLATE utf8_bin DEFAULT NULL COMMENT '查勘结论',
  `report_no` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '报案号',
  `order_no` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '订单号',
  `beijing_flag` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '北京互碰垫付标志 是:1 否0',
  `devolve_flag` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '委托索赔标志 是:1 否0',
  `big_flag` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '大案标志 是:1 否0',
  `payInfo_flag` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '支付标志 是:1 否0定',
  `estimate_loss_amount` decimal(16,2) DEFAULT NULL COMMENT '查勘估算金额',
  PRIMARY KEY (`id`),
  KEY `idx_survey_reportno` (`report_no`),
  KEY `idx_survey_orderno` (`order_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='查勘信息';
