CREATE TABLE `fh_part_item` (
  `created_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '创建人',
  `created_date` datetime NOT NULL COMMENT '创建日期',
  `updated_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '修改人',
  `updated_date` datetime NOT NULL COMMENT '修改日期',
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '表ID',
  `loss_id` bigint(20) NOT NULL COMMENT '订单号',
  `insure_code` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '险种名称',
  `part_no` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '配件编号',
  `part_name` varchar(200) COLLATE utf8_bin NOT NULL COMMENT '配件名称',
  `part_amount` decimal(16,2) DEFAULT NULL COMMENT '专修价',
  `market_price` decimal(16,2) DEFAULT NULL COMMENT '市场价',
  `loss_price` decimal(16,2) DEFAULT NULL COMMENT '定损单价',
  `loss_count` int(10) DEFAULT NULL COMMENT '定损数量',
  `part_salvage` decimal(16,2) DEFAULT NULL COMMENT '定损配置残值',
  `total_amount` decimal(16,2) DEFAULT NULL COMMENT '定损总额',
  `audit_price` decimal(16,2) DEFAULT NULL COMMENT '核损价格',
  `audit_count` int(10) DEFAULT NULL COMMENT '核损数量',
  `audit_salvage` decimal(16,2) DEFAULT NULL COMMENT '核损残值',
  `audit_amount` decimal(16,2) DEFAULT NULL COMMENT '核损总额',
  `callback_flag` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '是否回收',
  `first_amount` decimal(16,2) DEFAULT NULL COMMENT '第一次定损总额',
  `self_define` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '配件类型：自定配件为',
  `factory_part_no` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '原厂配件代码',
  PRIMARY KEY (`id`),
  KEY `idx_part_lossid` (`loss_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='定损配件项目信息';