CREATE TABLE `fh_loss_info` (
  `created_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '创建人',
  `created_date` datetime NOT NULL COMMENT '创建日期',
  `updated_by` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '修改人',
  `updated_date` datetime NOT NULL COMMENT '修改日期',
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '表ID',
  `order_no` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '订单号',
  `report_no` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '报案号',
  `car_id` bigint(20) DEFAULT NULL COMMENT '定损车ID',
  `loss_type` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '定损类型  1=定损 2=物损',
  `loss_target` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '损失目标  1=标的 2=三者',
  `is_all_loss` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '是否全损',
  `loss_place` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '损失部位',
  `insure_date` datetime DEFAULT NULL COMMENT '承保日期',
  `other_force_amount` decimal(16,2) DEFAULT NULL COMMENT '其他交强险赔款金额',
  `loss_desp` varchar(500) COLLATE utf8_bin DEFAULT NULL COMMENT '定损说明 描述',
  `loss_markup_rate` decimal(16,2) DEFAULT NULL COMMENT '配件定损加价率',
  `loss_markup_amount` decimal(16,2) DEFAULT NULL COMMENT '配件定损加价金额',
  `audit_markup_rate` decimal(16,2) DEFAULT NULL COMMENT '配件核价加价率',
  `audit_markup_amount` decimal(16,2) DEFAULT NULL COMMENT '配件核价加价金额',
  `part_loss_amount` decimal(16,2) DEFAULT NULL COMMENT '配件定损总额',
  `part_audit_amount` decimal(16,2) DEFAULT NULL COMMENT '配件核损总额',
  `repair_loss_amount` decimal(16,2) DEFAULT NULL COMMENT '维修工时费定损总额',
  `repair_audit_amount` decimal(16,2) DEFAULT NULL COMMENT '维修工时费核损总额',
  `fee_loss_amount` decimal(16,2) DEFAULT NULL COMMENT '费用项目定损总额',
  `fee_audit_amount` decimal(16,2) DEFAULT NULL COMMENT '费用项目核损总额',
  `loss_total_amount` decimal(16,2) DEFAULT NULL COMMENT '定损总额',
  `damage_loss_amount` decimal(16,2) DEFAULT NULL COMMENT '物损项目定损总额',
  `damage_audit_amount` decimal(16,2) DEFAULT NULL COMMENT '物损项目核损总额',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_loss_orderno` (`order_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='定损信息';